- name: Run ZAP baseline scan (uses zaproxy/action-baseline)
  uses: zaproxy/action-baseline@v0.14.0
  with:
    target: ${{ steps.vars.outputs.target }}
    # optional: docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
    # optional: rules_file_name: '.zap/rules.tsv'
    # optional: cmd_options: '-a'
  continue-on-error: true

- name: Save ZAP reports with timestamp
  if: always()
  run: |
    TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")
    mkdir -p scan-results
    if [ -f zap_report.html ]; then
      mv zap_report.html "scan-results/zap_report_${TIMESTAMP}.html"
      echo "Saved scan-results/zap_report_${TIMESTAMP}.html"
    else
      echo "No zap_report.html found"
    fi
    if [ -f zap_report.json ]; then
      mv zap_report.json "scan-results/zap_report_${TIMESTAMP}.json"
      echo "Saved scan-results/zap_report_${TIMESTAMP}.json"
    else
      echo "No zap_report.json found"
    fi
    ls -la scan-results || true
