name: Security Scan (ZAP baseline) - Action-based (Fixed)

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL (overrides TARGET_URL secret / env)'
        required: false
        default: ''
      fail_high_threshold:
        description: 'Fail if ZAP High alerts >= (default 3)'
        required: false
        default: '3'
      fail_critical_threshold:
        description: 'Fail if ZAP Critical alerts >= (default 1)'
        required: false
        default: '1'

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    env:
      OUTDIR: scan-results
      TARGET_URL: ${{ secrets.TARGET_URL || '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine target (input -> env -> secret)
        id: vars
        run: |
          INPUT="${{ github.event.inputs.target_url }}"
          IF_EMPTY() { [ -z "$1" ] && echo "$2" || echo "$1"; }
          TARGET="$(IF_EMPTY "$INPUT" "$TARGET_URL")"
          if [ -z "$TARGET" ]; then
            TARGET="${{ secrets.TARGET_URL || '' }}"
          fi
          if [ -z "$TARGET" ]; then
            echo "No target specified: set TARGET_URL secret or pass target_url when running the workflow."
            exit 1
          fi
          echo "target=$TARGET" >> $GITHUB_OUTPUT
          echo "fail_high=${{ github.event.inputs.fail_high_threshold }}" >> $GITHUB_OUTPUT
          echo "fail_crit=${{ github.event.inputs.fail_critical_threshold }}" >> $GITHUB_OUTPUT

      - name: Create output directory & install jq
        run: |
          mkdir -p $OUTDIR
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Run ZAP baseline scan (uses zaproxy/action-baseline)
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ steps.vars.outputs.target }}
          artifact_name: zap_report
          allow_issue_writing: 'false'       # avoid trying to create issues (permission error)
          fail_action: 'warn'                # optional: do not fail the job on scan alerts
        continue-on-error: true

      - name: Collect any generated report files into scan-results
        if: always()
        run: |
          set -euo pipefail
          mkdir -p scan-results
          # find any plausible ZAP outputs (html/json) produced by the action (search depth 3)
          find . -maxdepth 3 -type f \( -iname '*zap*report*.html' -o -iname '*zap*report*.json' -o -iname '*.html' -o -iname '*.json' \) -print > /tmp/zap_files.txt || true
          echo "Files discovered by find:"
          cat /tmp/zap_files.txt || true
          # copy discovered files into scan-results
          while IFS= read -r f; do
            cp -v "$f" scan-results/ || true
          done < /tmp/zap_files.txt || true
          echo "Contents of scan-results:"
          ls -la scan-results || true

      - name: Upload scan results artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: scan-results

      - name: Fail if High/Critical alerts >= thresholds
        if: always()
        run: |
          set -euo pipefail
          ZAP_JSON=$(ls -1 scan-results/*.json 2>/dev/null | tail -n1 || true)
          if [ -z "$ZAP_JSON" ]; then
            echo "No ZAP JSON report found in scan-results. Skipping threshold check."
            exit 0
          fi
          echo "Using ZAP JSON: $ZAP_JSON"
          HIGH_COUNT=$(jq '[.site[].alerts[] | select(.risk == "High")] | length' "$ZAP_JSON")
          CRIT_COUNT=$(jq '[.site[].alerts[] | select(.risk == "Critical")] | length' "$ZAP_JSON")
          echo "High Alerts: $HIGH_COUNT | Critical Alerts: $CRIT_COUNT"
          FAIL_HIGH=${{ steps.vars.outputs.fail_high }}
          FAIL_CRIT=${{ steps.vars.outputs.fail_crit }}
          echo "Thresholds: High >= $FAIL_HIGH, Critical >= $FAIL_CRIT"
          if [ "$HIGH_COUNT" -ge "$FAIL_HIGH" ] || [ "$CRIT_COUNT" -ge "$FAIL_CRIT" ]; then
            echo "Threshold exceeded — failing job"
            exit 1
          fi
          echo "No threshold violations — job will be marked successful."
